WebApplication5/Models/Product.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace WebApplication5.Models
{
    public class Product
    {
        public int id { get; set; }
        [Required]
        public string name { get; set; }
        public string description { get; set; }
        [Required]
        public double price { get; set; }
        public string image { get; set; }
        [DisplayName("Category")]
        public int? categoryid { get; set; }
        public Category category { get; set; }
    }
}

WebApplication5/Areas/Dashboard/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication5.Data;
using WebApplication5.Models;

namespace WebApplication5.Areas.Dashboard.Controllers
{
    [Area("Dashboard")]
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProductsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Dashboard/Products
        public async Task<IActionResult> Index()
        {
            return View(await _context.Products.Include(x=>x.category)
                .ToListAsync());
        }

        // GET: Dashboard/Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .FirstOrDefaultAsync(m => m.id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Dashboard/Products/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Dashboard/Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Product product, IFormFile Image)
        {
            if (Image == null)
            {
                ModelState.AddModelError(nameof(Product.image), "Image is required.");
            }
            var imageFileName = Guid.NewGuid() + Path.GetExtension(Image.FileName);
            if (!Directory.Exists(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/Products")))

            {
                Directory.CreateDirectory(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/Products"));

            }
            var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/Products", imageFileName);

            await using (var stream = new FileStream(filePath, FileMode.Create))
            {
                await Image.CopyToAsync(stream);
            }
            product.image = $"/img/Products/{imageFileName}";
            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Dashboard/Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            var categories = await _context.categories.ToArrayAsync();
            ViewBag.categories = new SelectList(categories,"Id","Name");
            return View(product);
        }

        // POST: Dashboard/Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Product product, IFormFile Image)
        {

            if (id != product.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {

                try
                {
                    var oldproduct = await _context.Products.FirstOrDefaultAsync(x => x.id == id);
                    if (Image != null)
                    {

                        var imageFileName = Guid.NewGuid() + Path.GetExtension(Image.FileName);
                        if (!Directory.Exists(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/Products")))

                        {
                            Directory.CreateDirectory(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/Products"));

                        }
                        var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/Products", imageFileName);

                        await using (var stream = new FileStream(filePath, FileMode.Create))
                        {
                            await Image.CopyToAsync(stream);
                        }
                        oldproduct.image = $"/img/Products/{imageFileName}";

                    }
                    oldproduct.name = product.name;
                    oldproduct.description = product.description;
                    oldproduct.price = product.price;
                    oldproduct.categoryid = product.categoryid;

                    _context.Update(oldproduct);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Dashboard/Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .FirstOrDefaultAsync(m => m.id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Dashboard/Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Products.FindAsync(id);
            if (product != null)
            {
                _context.Products.Remove(product);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.id == id);
        }
    }
}

WebApplication5/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication5.Data;
using WebApplication5.Models;

namespace WebApplication5.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        public readonly ApplicationDbContext _context;
        public readonly UserManager<ApplicationUser> _userManager;
        public CartController(ApplicationDbContext context,UserManager<ApplicationUser> userManager)
        {
            _context = context;
          _userManager = userManager;

        }

        public async Task<IActionResult> Index()
        {
            var currentuser = await _userManager.GetUserAsync(HttpContext.User);

            var cart = await _context.Carts
                .Include(x => x.Product)
                .Where(x => x.UserId == currentuser.Id)
                .ToListAsync();
            double totalCost = 0;

            foreach (var cartItem in cart)
            {
                totalCost += cartItem.Product.price * cartItem.QTY;
            }

            ViewBag.TotalCost = totalCost;

            return View(cart);

        
        }
        public async Task<IActionResult> UpdateQty(int productId, int qty)
        {
            var product = await _context.Products.Where(x => x.id == productId).FirstOrDefaultAsync();

            if (product == null)
            {
                return BadRequest();
            }

            var currentuser = await _userManager.GetUserAsync(HttpContext.User);

            var cartItem = await _context.Carts.Where(x => x.UserId == currentuser.Id)
                .Where(x => x.ProductId == productId)
                .FirstOrDefaultAsync();

            if (cartItem == null)
            {
                return BadRequest();
            }

            cartItem.QTY = qty;
            _context.Carts.Update(cartItem);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
        public async Task<IActionResult> AddToCart(int productId,int qty = 1)
        {
            var currentuser = await _userManager.GetUserAsync(HttpContext.User);

            var product = await _context.Products.Where(x => x.id == productId).FirstOrDefaultAsync();
            if (product == null)
            {
                return BadRequest();
            }
            var cart=new Cart { ProductId = productId,QTY=qty,UserId=currentuser.Id};
            _context.Add(cart);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");        }
        public async Task<IActionResult> Remove(int id)
        {
            var cartItem = await _context.Carts.FindAsync(id);
            if (cartItem == null)
            {
                return BadRequest();
            }
            _context.Carts.Remove(cartItem);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

WebApplication5/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication5.Data;

namespace WebApplication5.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProductsController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var products=await _context.Products.ToListAsync();
            return View(products);
        }
        public async Task <IActionResult> Details(int id)
        {
            var product = await _context.Products.FirstOrDefaultAsync(x => x.id == id);
            if (product == null)
            {
                return NotFound();
            }
           
            return View(product);
        }
    }
}

WebApplication5/Views/Products/Details.cshtml
@model Product

@section PageTitle {
    <!-- Header-->
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">Product Details</h1>
                <p class="lead fw-normal text-white-50 mb-0">@Model.name</p>
            </div>
        </div>
    </header>
}

<section class="py-5">
    <div class="container mt-5 mb-5">
        <div class="card">
            <div class="row g-0">
                <div class="col-md-4 border-end">
                    <div class="d-flex flex-column justify-content-center">
                        <div class="main_image"> <img src="@Model.image" id="main_product_image" width="350"> </div>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="p-3 right-side">
                        <h3>@Model.name</h3>
                        <div class="mt-2 pr-3 content">
                            <p>
                                @Model.description
                            </p>
                        </div>
                        <h3>$@Model.price</h3>

                        <div class=""> <a asp-controller="Cart" asp-action="AddToCart" asp-route-productId="@Model.id" class="btn btn-outline-dark mt-auto">Add to Cart</a> </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

WebApplication5/Views/Products/Index.cshtml
@model List<Product>

@section PageTitle{
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">All Products</h1>
                <p class="lead fw-normal text-white-50 mb-0">With this shop hompeage template</p>
            </div>
        </div>
    </header>
}

<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

            @foreach (var product in Model)
            {
                <div class="col mb-5">
                    <div class="card h-100">
                        <!-- Sale badge-->
                        @* <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div> *@
                        <!-- Product image-->
                        <img class="card-img-top" src="@product.image" alt="@product.name" />
                        <!-- Product details-->
                        <div class="card-body p-4">
                            <div class="text-center">
                                <!-- Product name-->
                                <h5 class="fw-bolder">
                                    <a asp-controller="Products" asp-action="Details" asp-route-id="@product.id">@product.name</a>
                                </h5>
                                <!-- Product price-->
                                @* <span class="text-muted text-decoration-line-through">$@product.Price</span> *@
                                $@product.price
                            </div>
                        </div>
                        <!-- Product actions-->
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center">
                                <a asp-controller="Cart" asp-action="AddToCart" asp-route-productId="@product.id" class="btn btn-outline-dark mt-auto">Add to cart</a>
                            </div>
                        </div>
                    </div>
                </div>
            }

        </div>
    </div>
</section>