WebApplication5/Models/Order.cs
using Microsoft.AspNetCore.Identity;
using WebApplication5.Models;

namespace WebApplication5.Models
{
    public class Order
    {
        public int Id { get; set; }

        public string UserId { get; set; }
        public ApplicationUser User { get; set; }

        public int AddressId { get; set; }
        public Address Address { get; set; }

        public double Amount { get; set; }

        public string Status { get; set; }

        public DateTime CreatedAt { get; set; }
        public List<OrderProduct> OrderProducts { get; set; }

    }
}

WebApplication5/Areas/Dashboard/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication5.Data;
using WebApplication5.Models;

namespace WebApplication5.Areas.Dashboard.Controllers
{
    [Area("Dashboard")]
    public class OrdersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrdersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Dashboard/Orders
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Orders
                .Include(x=>x.OrderProducts)
                .Include(o => o.Address).Include(o => o.User);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Dashboard/Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(x=>x.OrderProducts)
                .ThenInclude(x=>x.Product)
                .Include(o => o.Address)
                .Include(o => o.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // GET: Dashboard/Orders/Create
        public IActionResult Create()
        {
            ViewData["AddressId"] = new SelectList(_context.Addresses, "Id", "Id");
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        // POST: Dashboard/Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserId,AddressId,Amount,Status,CreatedAt")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AddressId"] = new SelectList(_context.Addresses, "Id", "Id", order.AddressId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", order.UserId);
            return View(order);
        }

        // GET: Dashboard/Orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            ViewData["AddressId"] = new SelectList(_context.Addresses, "Id", "Id", order.AddressId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", order.UserId);
            return View(order);
        }

        // POST: Dashboard/Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserId,AddressId,Amount,Status,CreatedAt")] Order order)
        {
            if (id != order.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AddressId"] = new SelectList(_context.Addresses, "Id", "Id", order.AddressId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", order.UserId);
            return View(order);
        }

        // GET: Dashboard/Orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.Address)
                .Include(o => o.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Dashboard/Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var order = await _context.Orders.FindAsync(id);
            if (order != null)
            {
                _context.Orders.Remove(order);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
            return _context.Orders.Any(e => e.Id == id);
        }
    }
}

WebApplication5/Controllers/OrdersController.cs
using WebApplication5.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace WebApplication5.Controllers
{
    public class OrdersController : Controller
    {
        public readonly ApplicationDbContext _context;

        public OrdersController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var orders = await _context.Orders
                .Include(x => x.OrderProducts)
                .ToListAsync();

            return View(orders);
        }

        public async Task<IActionResult> Details(int id)
        {
            var order = await _context.Orders
                .Include(x => x.OrderProducts)
                .ThenInclude(x => x.Product)
                .Include(x => x.Address)
                .FirstOrDefaultAsync(x => x.Id == id);

            return View(order);
        }
    }
}

WebApplication5/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication5.Data;

namespace WebApplication5.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProductsController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var products=await _context.Products.ToListAsync();
            return View(products);
        }
        public async Task <IActionResult> Details(int id)
        {
            var product = await _context.Products.FirstOrDefaultAsync(x => x.id == id);
            if (product == null)
            {
                return NotFound();
            }
           
            return View(product);
        }
    }
}

WebApplication5/Views/Orders/Details.cshtml
@model Order

<section class="py-5">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5  justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <div class="top-status">
                            <h5>ORDER# @Model.Id</h5>
                        </div>
                        <div>
                            <h5>Address:</h5>
                            <p>@Model.Address.AdressLine @Model.Address.City @Model.Address.State - @Model.Address.PinCode</p>
                        </div>

                        <div>
                            <h5>Order Amount:</h5>
                            <p>$@Model.Amount</p>
                        </div>

                        <div>
                            <h5>Status:</h5>
                            <p>@Model.Status</p>
                        </div>
                    </div>
                </div>

                <div class="card mt-4"></div>
                <div class="card-body p-0 table-responsive">
                    <h4 class="p-3 mb-0">Product Description</h4>
                    <table class="table mb-0">
                        <thead>
                            <tr>
                                <th scope="col">Product Image</th>
                                <th scope="col">Product Name</th>
                                <th scope="col">Unit Price</th>
                                <th scope="col">Quantity</th>
                                <th scope="col">Total</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach(var orderProduct in Model.OrderProducts)
                            {
                                <tr>

                                    <th>
                                        <a asp-controller="Products" asp-action="Details" asp-route-id="@orderProduct.ProductId">
                                            <img width="200"
                                                 src="@orderProduct.Product.image"
                                                 alt="@orderProduct.Product.name">
                                        </a>
                                    </th>
                                    <td>
                                        <a asp-controller="Products" asp-action="Details" asp-route-id="@orderProduct.ProductId">@orderProduct.Product.name</a>
                                    </td>
                                    <td>@orderProduct.Price</td>
                                    <td>@orderProduct.Qty</td>
                                    <td><strong>$@(orderProduct.Price * orderProduct.Qty)</strong></td>
                                </tr>
                            }
                          
                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>
</section>

WebApplication5/Views/Orders/Index.cshtml
@model List<Order>

<section class="py-5">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5  justify-content-center">
            <div class="col-md-12">
                <h2 class="mb-4">Order List</h2>


                <!-- Order List Table -->
                <table class="table table-bordered table-hover">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">Order ID</th>
                            <th scope="col">Date</th>
                            <th scope="col">Status</th>
                            <th scope="col">Total</th>
                            <th scope="col">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <!-- Sample Order Row -->
                        @foreach(var order in Model)
                        {
                            <tr>
                            <td>@order.Id</td>
                            <td>@order.CreatedAt.ToShortDateString()</td>
                            <td>
                                    <span class="badge text-success">@order.Status</span>
                            </td>
                            <td>$@order.Amount</td>
                            <td>
                                <a asp-controller="Orders" asp-action="Details" asp-route-id="@order.Id" class="btn btn-primary btn-sm">View</a>
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>